/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zyj_play_pid_jni_MacJni */

#ifndef _Included_com_zyj_play_pid_jni_MacJni
#define _Included_com_zyj_play_pid_jni_MacJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zyj_play_pid_jni_MacJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zyj_play_pid_jni_MacJni_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
